# Generated by Django 6.0 on 2026-02-03 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_warehouse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='two_factor_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'الخطة المجانية'), ('basic', 'الخطة الأساسية'), ('professional', 'الخطة الاحترافية'), ('enterprise', 'خطة المؤسسات')], default='free', max_length=20)),
                ('status', models.CharField(default='active', max_length=20)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('renewal_date', models.DateField()),
                ('monthly_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('storage_used', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('storage_total', models.DecimalField(decimal_places=2, default=5, max_digits=10)),
                ('auto_renew', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
