# Generated by Django 6.0 on 2026-02-03 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_usersession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('action_type', models.CharField(choices=[('login_success', 'دخول ناجح'), ('login_failed', 'محاولة دخول فاشلة'), ('logout', 'تسجيل خروج'), ('permission_change', 'تغيير صلاحيات'), ('settings_change', 'تغيير إعدادات'), ('role_change', 'تغيير الدور'), ('user_created', 'إنشاء مستخدم'), ('user_deleted', 'حذف مستخدم'), ('data_export', 'تصدير بيانات'), ('password_change', 'تغيير كلمة المرور'), ('2fa_enabled', 'تفعيل أمان'), ('suspicious_activity', 'نشاط مشبوه'), ('multiple_failed', 'فشل متعدد')], max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('success', 'نجح'), ('warning', 'تحذير'), ('failed', 'فشل')], default='success', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سجل أمان',
                'verbose_name_plural': 'سجلات الأمان',
                'ordering': ['-timestamp'],
            },
        ),
    ]
