# Generated by Django 6.0 on 2026-02-03 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_securitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name_ar', models.CharField(blank=True, max_length=255)),
                ('company_name_en', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(default='SAR', max_length=20)),
                ('timezone', models.CharField(default='Asia/Riyadh', max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('tax_enabled', models.BooleanField(default=True)),
                ('vat_number', models.CharField(blank=True, max_length=50)),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=15, max_digits=5)),
                ('prices_include_tax', models.BooleanField(default=True)),
                ('show_vat_on_invoice', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات الشركة',
                'verbose_name_plural': 'إعدادات الشركة',
            },
        ),
    ]
