# Generated by Django 6.0 on 2026-02-03 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_companysettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('template_type', models.CharField(choices=[('sales_invoice', 'قالب فاتورة المبيعات'), ('purchase_order', 'قالب أمر الشراء'), ('inventory_report', 'قالب تقرير المخزون'), ('customer_statement', 'قالب بيان العميل')], max_length=50)),
                ('style', models.CharField(choices=[('standard', 'نموذج قياسي (A4)'), ('thermal', 'حراري / نقاط بيع'), ('minimal', 'نموذج عصري (مبسط)')], default='standard', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('show_qr_code', models.BooleanField(default=True)),
                ('show_signature', models.BooleanField(default=True)),
                ('show_vat', models.BooleanField(default=True)),
                ('header_title', models.CharField(default='فاتورة ضريبية', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'نموذج الطباعة',
                'verbose_name_plural': 'نماذج الطباعة',
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='notes',
            field=models.TextField(blank=True, help_text='ملاحظات أمر الشراء'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='includes_vat',
            field=models.BooleanField(default=True, help_text='هل الأسعار تشمل ضريبة القيمة المضافة'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='notes',
            field=models.TextField(blank=True, help_text='ملاحظات الفاتورة - تظهر في أسفل الفاتورة'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='print_template',
            field=models.ForeignKey(blank=True, limit_choices_to={'template_type': 'purchase_order'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='core.printtemplate'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='print_template',
            field=models.ForeignKey(blank=True, limit_choices_to={'template_type': 'sales_invoice'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_invoices', to='core.printtemplate'),
        ),
    ]
