# Generated by Django 6.0 on 2026-02-03 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_printtemplate_purchaseorder_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='seal',
            field=models.ImageField(blank=True, null=True, upload_to='company/seals/'),
        ),
    ]
