# Generated by Django 6.0 on 2026-02-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_companysettings_seal'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='default_print_template',
            field=models.CharField(choices=[('classic', 'النموذج الكلاسيكي'), ('modern', 'النموذج العصري'), ('minimal', 'النموذج المبسط')], default='classic', max_length=50),
        ),
    ]
