# Generated by Django 6.0 on 2026-02-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_companysettings_default_print_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='storage_quota_mb',
            field=models.FloatField(default=10240),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='storage_used_mb',
            field=models.FloatField(default=0),
        ),
    ]
