# Generated by Django 6.0 on 2026-02-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_companysettings_notification_preferences_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='renewal_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
