# Generated by Django 6.0 on 2026-02-04 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_ssoconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='calendar_type',
            field=models.CharField(choices=[('gregorian', 'ميلادي (Gregorian)'), ('hijri', 'هجري (Hijri)'), ('both', 'كلاهما')], default='gregorian', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_format',
            field=models.CharField(choices=[('dmy', 'DD/MM/YYYY'), ('mdy', 'MM/DD/YYYY'), ('ymd', 'YYYY-MM-DD')], default='dmy', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='report_language',
            field=models.CharField(choices=[('ar', 'العربية'), ('en', 'English'), ('dual', 'ثنائي اللغة (Ar/En)')], default='ar', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='system_language',
            field=models.CharField(choices=[('ar', 'العربية (الأصلية)'), ('en', 'English (US)'), ('fr', 'Français')], default='ar', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(choices=[('riyadh', '(GMT+03:00) الرياض، السعودية'), ('dubai', '(GMT+04:00) دبي، الإمارات'), ('cairo', '(GMT+02:00) القاهرة، مصر')], default='riyadh', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='use_24hour_format',
            field=models.BooleanField(default=True),
        ),
    ]
